BINANCE_WEBHOOK_PASSPHRASE = "somelongstring123"
BINANCE_API_KEY = 'ioQDXsEA3lfdXbiJ83s29SqheaHtgRWGTht8cFhSukFQ2n58z5G4QyuZy1ez9O3j'
BINANCE_API_SECRET = 'TGBjNd2DhzytIcAlBspuiNXYMO4AqwYuaWcl4w7eyGRMsX0RqCFCjNkG5o96Pw0N'

XTB_USER_ID = "user"
XTB_USER_PASS = "pass"

XBKR_USER_ID = "user"
XBKR_USER_PASS = "pass"